name: Dart

on:
  push:
    branches: [main]
    paths:
      - "dart/**"
      - "spec/**"
      - "justfile"
      - ".tool-versions"
      - ".mise.toml"
      - ".github/workflows/dart.yml"
  pull_request:
    paths:
      - "dart/**"
      - "spec/**"
      - "justfile"
      - ".tool-versions"
      - ".mise.toml"
      - ".github/workflows/dart.yml"

jobs:
  format:
    name: Format & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@v5
        with:
          install_args: dart just
      - name: Install dependencies
        run: dart pub get
        working-directory: dart
      - name: Format & Lint
        run: just lint-dart

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@v5
        with:
          install_args: dart just nodejs
      - name: Test
        run: just test-dart
